name: rarecoinradar_app
description: >
  RareCoinRadar AI Web App — Analyze coin resale value, generate SEO listings, 
  estimate profit margins, and export custom reports with advanced animations.

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP and Web Support
  http: ^1.2.1
  url_launcher: ^6.2.5
  universal_html: ^2.2.3

  # State Management & Utils
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  collection: ^1.18.0

  # UI / UX Animations & Design
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  responsive_framework: ^1.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # JSON, Logic, and AI Placeholder Support
  json_annotation: ^4.9.0

  # PDF / CSV / Clipboard (for future download/copy/export)
  printing: ^5.12.0
  csv: ^5.0.2
  universal_io: ^2.2.2
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/mock/

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
      - asset: assets/fonts/Inter-Bold.ttf
